### Get all Books
GET http://localhost:4000/books
Accept: application/json

### Get a Book by ID
GET http://localhost:4000/books/2
Accept: application/json

### Save a new Book
POST http://localhost:4000/books/save
Content-Type: application/json

{
  "title": "Arco Iris",
  "author": "Juan Salvador Gaviota",
  "description": "A tale of love, wealth, and tragedy during the Roaring Twenties.",
  "category": "Classic",
  "stock": 20,
  "price": 30.99,
  "status": 1
}






### Update a book
PUT http://localhost:4000/books/4
Content-Type: application/json

{
  "title": "Test Update",
  "author": "Test Update",
  "description": "Test Update",
  "category": "Test Update",
  "stock": 15,
  "price": 32,
  "status": 1
}

### Delete book by ID
DELETE http://localhost:4000/books/3
Accept: application/json